/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as MatchesRouteImport } from './routes/matches'
import { Route as MapRouteImport } from './routes/map'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GarageRouteImport } from './routes/garage'
import { Route as FeedRouteImport } from './routes/feed'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as AddVehicleRouteImport } from './routes/add-vehicle'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EventsIndexRouteImport } from './routes/events.index'
import { Route as VehicleIdRouteImport } from './routes/vehicle.$id'
import { Route as UUsernameRouteImport } from './routes/u.$username'
import { Route as EventsNewRouteImport } from './routes/events.new'

const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchesRoute = MatchesRouteImport.update({
  id: '/matches',
  path: '/matches',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GarageRoute = GarageRouteImport.update({
  id: '/garage',
  path: '/garage',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedRoute = FeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AddVehicleRoute = AddVehicleRouteImport.update({
  id: '/add-vehicle',
  path: '/add-vehicle',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const VehicleIdRoute = VehicleIdRouteImport.update({
  id: '/vehicle/$id',
  path: '/vehicle/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const UUsernameRoute = UUsernameRouteImport.update({
  id: '/u/$username',
  path: '/u/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsNewRoute = EventsNewRouteImport.update({
  id: '/events/new',
  path: '/events/new',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/add-vehicle': typeof AddVehicleRoute
  '/chat': typeof ChatRoute
  '/explore': typeof ExploreRoute
  '/feed': typeof FeedRoute
  '/garage': typeof GarageRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/matches': typeof MatchesRoute
  '/profile': typeof ProfileRoute
  '/events/new': typeof EventsNewRoute
  '/u/$username': typeof UUsernameRoute
  '/vehicle/$id': typeof VehicleIdRoute
  '/events/': typeof EventsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/add-vehicle': typeof AddVehicleRoute
  '/chat': typeof ChatRoute
  '/explore': typeof ExploreRoute
  '/feed': typeof FeedRoute
  '/garage': typeof GarageRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/matches': typeof MatchesRoute
  '/profile': typeof ProfileRoute
  '/events/new': typeof EventsNewRoute
  '/u/$username': typeof UUsernameRoute
  '/vehicle/$id': typeof VehicleIdRoute
  '/events': typeof EventsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/add-vehicle': typeof AddVehicleRoute
  '/chat': typeof ChatRoute
  '/explore': typeof ExploreRoute
  '/feed': typeof FeedRoute
  '/garage': typeof GarageRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/matches': typeof MatchesRoute
  '/profile': typeof ProfileRoute
  '/events/new': typeof EventsNewRoute
  '/u/$username': typeof UUsernameRoute
  '/vehicle/$id': typeof VehicleIdRoute
  '/events/': typeof EventsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/add-vehicle'
    | '/chat'
    | '/explore'
    | '/feed'
    | '/garage'
    | '/login'
    | '/map'
    | '/matches'
    | '/profile'
    | '/events/new'
    | '/u/$username'
    | '/vehicle/$id'
    | '/events/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/add-vehicle'
    | '/chat'
    | '/explore'
    | '/feed'
    | '/garage'
    | '/login'
    | '/map'
    | '/matches'
    | '/profile'
    | '/events/new'
    | '/u/$username'
    | '/vehicle/$id'
    | '/events'
  id:
    | '__root__'
    | '/'
    | '/add-vehicle'
    | '/chat'
    | '/explore'
    | '/feed'
    | '/garage'
    | '/login'
    | '/map'
    | '/matches'
    | '/profile'
    | '/events/new'
    | '/u/$username'
    | '/vehicle/$id'
    | '/events/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddVehicleRoute: typeof AddVehicleRoute
  ChatRoute: typeof ChatRoute
  ExploreRoute: typeof ExploreRoute
  FeedRoute: typeof FeedRoute
  GarageRoute: typeof GarageRoute
  LoginRoute: typeof LoginRoute
  MapRoute: typeof MapRoute
  MatchesRoute: typeof MatchesRoute
  ProfileRoute: typeof ProfileRoute
  EventsNewRoute: typeof EventsNewRoute
  UUsernameRoute: typeof UUsernameRoute
  VehicleIdRoute: typeof VehicleIdRoute
  EventsIndexRoute: typeof EventsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matches': {
      id: '/matches'
      path: '/matches'
      fullPath: '/matches'
      preLoaderRoute: typeof MatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/garage': {
      id: '/garage'
      path: '/garage'
      fullPath: '/garage'
      preLoaderRoute: typeof GarageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed': {
      id: '/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof FeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add-vehicle': {
      id: '/add-vehicle'
      path: '/add-vehicle'
      fullPath: '/add-vehicle'
      preLoaderRoute: typeof AddVehicleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/': {
      id: '/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vehicle/$id': {
      id: '/vehicle/$id'
      path: '/vehicle/$id'
      fullPath: '/vehicle/$id'
      preLoaderRoute: typeof VehicleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$username': {
      id: '/u/$username'
      path: '/u/$username'
      fullPath: '/u/$username'
      preLoaderRoute: typeof UUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/new': {
      id: '/events/new'
      path: '/events/new'
      fullPath: '/events/new'
      preLoaderRoute: typeof EventsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddVehicleRoute: AddVehicleRoute,
  ChatRoute: ChatRoute,
  ExploreRoute: ExploreRoute,
  FeedRoute: FeedRoute,
  GarageRoute: GarageRoute,
  LoginRoute: LoginRoute,
  MapRoute: MapRoute,
  MatchesRoute: MatchesRoute,
  ProfileRoute: ProfileRoute,
  EventsNewRoute: EventsNewRoute,
  UUsernameRoute: UUsernameRoute,
  VehicleIdRoute: VehicleIdRoute,
  EventsIndexRoute: EventsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
